title: 'Trail Course Of C '
description: Trail course
template:
  repo: trail-course-of-c-template
  name: trail-course-of-c
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
